# solely for db

services:
  postgres-dev:
    image: postgres:latest
    container_name: postgres-dev
    environment:
      POSTGRES_USER: fare_dev_user
      POSTGRES_PASSWORD: fare_dev_password
      POSTGRES_DB: fare_dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data_dev:
