import React from 'react';
import Navbar from '@/components/shared/Navbar';
import '../globals.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <section className="main-container">
          <div className="w-full max-w-4xl">{children}</div>
        </section>
      </body>
    </html>
  );
}
