name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "21"

      - name: Start Docker Compose
        run: docker compose -f backend/docker-compose.yml up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          while ! nc -z localhost 5432; do
            sleep 1
          done
          echo "PostgreSQL is ready."

      - name: Run Maven tests
        run: mvn test
        working-directory: backend

      - name: Check test coverage
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: backend/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 70
          min-coverage-changed-files: 70
          title: Code Coverage

      - name: Stop Docker Compose
        run: docker compose -f backend/docker-compose.yml down
